/*
 * Copyright © 2019 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
import {
  mdiAccountCogOutline,
  mdiAccountMultiple,
  mdiAccountOutline,
  mdiAccountStarOutline,
  mdiAlertOutline,
  mdiArrangeSendBackward,
  mdiArrowCollapseUp,
  mdiArrowRightBold,
  mdiBankOutline,
  mdiBarcode,
  mdiBell,
  mdiBookEditOutline,
  mdiBookOffOutline,
  mdiBookOpenVariant,
  mdiBookRemoveOutline,
  mdiCakeVariant,
  mdiCalculator,
  mdiCalendar,
  mdiCalendarCheck,
  mdiCalendarClock,
  mdiCalendarMonth,
  mdiCalendarQuestion,
  mdiCalendarRemove,
  mdiCalendarStar,
  mdiCalendarWeek,
  mdiCardAccountDetailsOutline,
  mdiCardsOutline,
  mdiCertificateOutline,
  mdiChartPie,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckUnderline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCityVariantOutline,
  mdiClipboardCheckOutline,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircleOutline,
  mdiCloudUpload,
  mdiCogs,
  mdiCommentAlertOutline,
  mdiCurrencyJpy,
  mdiDeleteOutline,
  mdiDomain,
  mdiDotsHorizontalCircleOutline,
  mdiDotsVertical,
  mdiDownload,
  mdiDragHorizontal,
  mdiEmailOutline,
  mdiEmoticonConfusedOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileDocumentOutline,
  mdiFileExcelOutline,
  mdiFilePdfBox,
  mdiFileTableBoxOutline,
  mdiFileTableOutline,
  mdiFilter,
  mdiFlagOutline,
  mdiFormatListChecks,
  mdiFormatListText,
  mdiHelpBox,
  mdiHelpCircleOutline,
  mdiHumanCane,
  mdiHumanMaleFemale,
  mdiLock,
  mdiMagnify,
  mdiMapMarkerOutline,
  mdiMinusCircleOffOutline,
  mdiMinusCircleOutline,
  mdiNotebookEditOutline,
  mdiNumeric,
  mdiPauseCircleOutline,
  mdiPencil,
  mdiPhone,
  mdiPlaylistEdit,
  mdiPlus,
  mdiPoll,
  mdiPoundBoxOutline,
  mdiRefresh,
  mdiRepeat,
  mdiSend,
  mdiShieldKeyOutline,
  mdiTargetVariant,
  mdiText,
  mdiTimerSand,
  mdiTimetable,
  mdiUndoVariant,
  mdiViewDashboard,
  mdiWalk,
  mdiWalletMembership,
  mdiWalletOutline
} from '@mdi/js'
import { mdiCalendarRange } from '@mdi/js/commonjs/mdi'
import { defineNuxtPlugin } from '@nuxtjs/composition-api'

// @mdi/js には https://material.io/resources/icons/ の accessible に該当するアイコンの定義がない
// どうやら http://accessibleicon.org/ 絡みらしい……がわかりやすさを優先して独自に定義して用いることにする
const accessible = 'M10 4a2 2 0 104 0 2 2 0 10-4 0M19 13v-2c-1.54.02-3.09-.75-4.07-1.83l-1.29-1.43c-.17-.19-.38-.34-.61-.45-.01 0-.01-.01-.02-.01H13c-.35-.2-.75-.3-1.19-.26C10.76 7.11 10 8.04 10 9.09V15c0 1.1.9 2 2 2h5v5h2v-5.5c0-1.1-.9-2-2-2h-3v-3.45c1.29 1.07 3.25 1.94 5 1.95zm-6.17 5c-.41 1.16-1.52 2-2.83 2-1.66 0-3-1.34-3-3 0-1.31.84-2.41 2-2.83V12.1a5 5 0 105.9 5.9h-2.07z'

// アイコン一覧にあるのに何故か @mdi/js に定義がない
const mdiProgressPencil = 'M15.84 10.2L14.83 11.21L12.76 9.18L13.77 8.16C13.97 7.95 14.31 7.94 14.55 8.16L15.84 9.41C16.05 9.62 16.06 9.96 15.84 10.2M8 13.91L12.17 9.72L14.24 11.8L10.08 16H8V13.91M13 2V4C17.39 4.54 20.5 8.53 19.96 12.92C19.5 16.56 16.64 19.43 13 19.88V21.88C18.5 21.28 22.45 16.34 21.85 10.85C21.33 6.19 17.66 2.5 13 2M11 2C9.04 2.18 7.19 2.95 5.67 4.2L7.1 5.74C8.22 4.84 9.57 4.26 11 4.06V2.06M4.26 5.67C3 7.19 2.24 9.04 2.05 11H4.05C4.24 9.58 4.8 8.23 5.69 7.1L4.26 5.67M2.06 13C2.26 14.96 3.03 16.81 4.27 18.33L5.69 16.9C4.81 15.77 4.24 14.42 4.06 13H2.06M7.06 18.37L5.67 19.74C7.18 21 9.04 21.79 11 22V20C9.58 19.82 8.23 19.25 7.1 18.37H7.06Z'

export const $icons = {
  add: mdiPlus,
  addr: mdiMapMarkerOutline,
  admin: mdiShieldKeyOutline,
  alert: mdiAlertOutline,
  amount: mdiPoll,
  back: mdiChevronLeft,
  bank: mdiBankOutline,
  billing: mdiCalculator,
  birthday: mdiCakeVariant,
  blank: '',
  carePlanAuthor: mdiNotebookEditOutline,
  category: mdiCardsOutline,
  certification: mdiCertificateOutline,
  city: mdiCityVariantOutline,
  close: mdiClose,
  completed: mdiCheckCircle,
  comprehensiveService: mdiWalk,
  confirmed: mdiCheckCircle,
  copayLimit: mdiArrowCollapseUp,
  copy: mdiArrangeSendBackward,
  csv: mdiFileTableOutline,
  dashboard: mdiViewDashboard,
  date: mdiCalendar,
  dateEnd: mdiCalendarRemove,
  dateRange: mdiCalendarRange,
  dateStart: mdiCalendarCheck,
  dayOfWeek: mdiCalendarWeek,
  days: mdiCalendarQuestion,
  defrayerCategory: mdiWalletMembership,
  delete: mdiDeleteOutline,
  disableContract: mdiBookOffOutline,
  document: mdiFileDocumentOutline,
  download: mdiDownload,
  dws: accessible,
  dwsNumber: mdiBarcode,
  dwsType: mdiEmoticonConfusedOutline,
  edit: mdiPencil,
  editVariant: mdiPlaylistEdit,
  editContract: mdiBookEditOutline,
  email: mdiEmailOutline,
  employeeNumber: mdiCardAccountDetailsOutline,
  expand: mdiChevronDown,
  filter: mdiFilter,
  fix: mdiCheckUnderline,
  forward: mdiChevronRight,
  headcount: mdiAccountMultiple,
  help: mdiHelpBox,
  id: mdiPoundBoxOutline,
  invisible: mdiEyeOffOutline,
  issuedOn: mdiCalendarStar,
  keyword: mdiMagnify,
  ledger: mdiBookOpenVariant,
  level: mdiPoll,
  ltcs: mdiHumanCane,
  ltcsInsNumber: mdiBarcode,
  month: mdiCalendarMonth,
  more: mdiDotsVertical,
  moveRight: mdiArrowRightBold,
  note: mdiText,
  notification: mdiBell,
  number: mdiPoundBoxOutline,
  objective: mdiFlagOutline,
  office: mdiDomain,
  ownExpenseProgram: mdiFormatListText,
  password: mdiLock,
  pdf: mdiFilePdfBox,
  personalName: mdiAccountOutline,
  problem: mdiCommentAlertOutline,
  provisionReport: mdiClipboardCheckOutline,
  ratio: mdiChartPie,
  recipientNumber: mdiBarcode,
  recurrence: mdiRepeat,
  refresh: mdiRefresh,
  request: mdiAccountStarOutline,
  role: mdiAccountCogOutline,
  save: mdiCloudUpload,
  schedule: mdiCalendarClock,
  scope: mdiTargetVariant,
  score: mdiFileTableBoxOutline,
  send: mdiSend,
  serviceCode: mdiNumeric,
  serviceOption: mdiFormatListChecks,
  settings: mdiCogs,
  sex: mdiHumanMaleFemale,
  shift: mdiTimetable,
  shrink: mdiChevronUp,
  sortable: mdiDragHorizontal,
  staff: mdiAccountOutline,
  statusChecking: mdiProgressPencil,
  statusDisabled: mdiMinusCircleOffOutline,
  statusNotAvailable: mdiMinusCircleOutline,
  statusProgress: mdiDotsHorizontalCircleOutline,
  statusReady: mdiDotsHorizontalCircleOutline,
  statusRejected: mdiCloseCircleOutline,
  statusResolved: mdiCheckCircleOutline,
  statusSuspended: mdiPauseCircleOutline,
  statusUnknown: mdiHelpCircleOutline,
  tel: mdiPhone,
  terminateContract: mdiBookRemoveOutline,
  text: mdiText,
  timeAmount: mdiTimerSand,
  timeframe: mdiClockOutline,
  undo: mdiUndoVariant,
  upload: mdiCloudUpload,
  user: accessible,
  visible: mdiEyeOutline,
  wallet: mdiWalletOutline,
  xlsx: mdiFileExcelOutline,
  yen: mdiCurrencyJpy
}

/**
 * アイコンプラグイン.
 */
export default defineNuxtPlugin((_, inject) => {
  inject('icons', $icons)
})
