/*
 * Copyright © 2021 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
import { createSeeds, ID_MAX, ID_MIN, STUB_COUNT } from '~~/stubs'

export const LTCS_BILLING_ID_MAX = ID_MAX
export const LTCS_BILLING_ID_MIN = ID_MIN
export const LTCS_BILLING_STUB_COUNT = STUB_COUNT

export const LTCS_BILLING_BUNDLE_STUB_COUNT_PER_BILLING = 2
export const LTCS_BILLING_BUNDLE_STUB_COUNT = LTCS_BILLING_STUB_COUNT * LTCS_BILLING_BUNDLE_STUB_COUNT_PER_BILLING

export const LTCS_BILLING_INVOICE_STUB_COUNT_PER_BUNDLE = 2
export const LTCS_BILLING_INVOICE_STUB_COUNT =
  LTCS_BILLING_BUNDLE_STUB_COUNT * LTCS_BILLING_INVOICE_STUB_COUNT_PER_BUNDLE

export const LTCS_BILLING_STATEMENT_ID_MIN = ID_MIN
export const LTCS_BILLING_STATEMENT_STUB_COUNT_PER_INVOICE = 10
export const LTCS_BILLING_STATEMENT_STUB_COUNT =
  LTCS_BILLING_INVOICE_STUB_COUNT * LTCS_BILLING_STATEMENT_STUB_COUNT_PER_INVOICE

export const LTCS_BILLING_SEEDS = createSeeds(Math.max(
  LTCS_BILLING_STUB_COUNT,
  LTCS_BILLING_BUNDLE_STUB_COUNT,
  LTCS_BILLING_INVOICE_STUB_COUNT,
  LTCS_BILLING_STATEMENT_STUB_COUNT
))
