/*
 * Copyright © 2021 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
import { createSeeds, ID_MAX, ID_MIN, STUB_COUNT } from '~~/stubs'

export const DWS_BILLING_ID_MAX = ID_MAX
export const DWS_BILLING_ID_MIN = ID_MIN
export const DWS_BILLING_STUB_COUNT = STUB_COUNT

export const DWS_BILLING_BUNDLE_STUB_COUNT_PER_BILLING = 10
export const DWS_BILLING_BUNDLE_STUB_COUNT = DWS_BILLING_STUB_COUNT * DWS_BILLING_BUNDLE_STUB_COUNT_PER_BILLING

export const DWS_BILLING_STATEMENT_ID_MIN = ID_MIN
export const DWS_BILLING_STATEMENT_STUB_COUNT_PER_BUNDLE = 20
export const DWS_BILLING_STATEMENT_STUB_COUNT =
  DWS_BILLING_BUNDLE_STUB_COUNT * DWS_BILLING_STATEMENT_STUB_COUNT_PER_BUNDLE

export const DWS_BILLING_SERVICE_REPORT_STUB_COUNT_PER_BUNDLE = 20
export const DWS_BILLING_SERVICE_REPORT_STUB_COUNT =
  DWS_BILLING_BUNDLE_STUB_COUNT * DWS_BILLING_SERVICE_REPORT_STUB_COUNT_PER_BUNDLE

export const DWS_BILLING_SERVICE_REPORT_ITEM_STUB_COUNT_PER_REPORT = 20
export const DWS_BILLING_SERVICE_REPORT_ITEM_STUB_COUNT =
  DWS_BILLING_SERVICE_REPORT_STUB_COUNT * DWS_BILLING_SERVICE_REPORT_ITEM_STUB_COUNT_PER_REPORT

export const DWS_BILLING_SEEDS = createSeeds(Math.max(
  DWS_BILLING_STUB_COUNT,
  DWS_BILLING_BUNDLE_STUB_COUNT,
  DWS_BILLING_STATEMENT_STUB_COUNT,
  DWS_BILLING_SERVICE_REPORT_STUB_COUNT,
  DWS_BILLING_SERVICE_REPORT_ITEM_STUB_COUNT
))
