<?php
/**
 * Copyright © 2019 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
declare(strict_types=1);

namespace Tests\Unit\Examples;

use Domain\Common\Carbon;
use Domain\Permission\Permission;
use Domain\Role\Role;
use Domain\Role\RoleScope;
use Faker\Generator;
use ScalikePHP\Seq;

/**
 * Role Examples.
 *
 * @property-read Role[] $roles
 * @mixin \Tests\Unit\Examples\OrganizationExample
 */
trait RoleExample
{
    /**
     * ロールの一覧を生成する.
     *
     * @return \Domain\Role\Role[]
     */
    protected function roles(): array
    {
        $allPermissions = Seq::fromArray(Permission::all())
            ->sortBy(fn (Permission $x): string => $x->value())
            ->toArray();
        return [
            $this->generateRole([
                'id' => 1,
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => true,
            ]),
            $this->generateRole([
                'id' => 2,
                'organizationId' => $this->organizations[0]->id,
                'permissions' => [Permission::viewInternalOffices()], // viewしかできないRoleにしていく
                'isSystemAdmin' => false,
            ]),
            $this->generateRole([
                'id' => 3,
                'organizationId' => $this->organizations[1]->id,
            ]),
            $this->generateRole([
                'id' => 4,
                'organizationId' => $this->organizations[0]->id,
                'permissions' => [
                ],
                'isSystemAdmin' => true,
            ]),
            $this->generateRole([
                'id' => 5,
                'name' => '人事担当者',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::whole(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                ],
            ]),
            $this->generateRole([
                'id' => 6,
                'name' => '総務担当者',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::whole(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createOfficeGroups(),
                    Permission::deleteOfficeGroups(),
                    Permission::listOfficeGroups(),
                    Permission::updateOfficeGroups(),
                    Permission::viewOfficeGroups(),
                    Permission::createInternalOffices(),
                    Permission::deleteInternalOffices(),
                    Permission::listInternalOffices(),
                    Permission::updateInternalOffices(),
                    Permission::viewInternalOffices(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                ],
            ]),
            $this->generateRole([
                'id' => 7,
                'name' => 'ブロックマネージャー',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::group(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createAttendances(),
                    Permission::deleteAttendances(),
                    Permission::listAttendances(),
                    Permission::updateAttendances(),
                    Permission::viewAttendances(),
                    Permission::createBillings(),
                    Permission::deleteBillings(),
                    Permission::downloadBillings(),
                    Permission::listBillings(),
                    Permission::updateBillings(),
                    Permission::viewBillings(),
                    Permission::listLtcsProvisionReports(),
                    Permission::updateLtcsProvisionReports(),
                    Permission::createOfficeGroups(),
                    Permission::deleteOfficeGroups(),
                    Permission::listOfficeGroups(),
                    Permission::updateOfficeGroups(),
                    Permission::viewOfficeGroups(),
                    Permission::createInternalOffices(),
                    Permission::deleteInternalOffices(),
                    Permission::listInternalOffices(),
                    Permission::updateInternalOffices(),
                    Permission::viewInternalOffices(),
                    Permission::createOwnExpensePrograms(),
                    Permission::listOwnExpensePrograms(),
                    Permission::updateOwnExpensePrograms(),
                    Permission::viewOwnExpensePrograms(),
                    Permission::createShifts(),
                    Permission::deleteShifts(),
                    Permission::importShifts(),
                    Permission::listShifts(),
                    Permission::updateShifts(),
                    Permission::viewShifts(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                    Permission::createUsers(),
                    Permission::deleteUsers(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 8,
                'name' => 'エリアマネージャー',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::group(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createAttendances(),
                    Permission::deleteAttendances(),
                    Permission::listAttendances(),
                    Permission::updateAttendances(),
                    Permission::viewAttendances(),
                    Permission::createBillings(),
                    Permission::deleteBillings(),
                    Permission::downloadBillings(),
                    Permission::listBillings(),
                    Permission::updateBillings(),
                    Permission::viewBillings(),
                    Permission::listLtcsProvisionReports(),
                    Permission::updateLtcsProvisionReports(),
                    Permission::createOfficeGroups(),
                    Permission::deleteOfficeGroups(),
                    Permission::listOfficeGroups(),
                    Permission::updateOfficeGroups(),
                    Permission::viewOfficeGroups(),
                    Permission::createInternalOffices(),
                    Permission::deleteInternalOffices(),
                    Permission::listInternalOffices(),
                    Permission::updateInternalOffices(),
                    Permission::viewInternalOffices(),
                    Permission::createOwnExpensePrograms(),
                    Permission::listOwnExpensePrograms(),
                    Permission::updateOwnExpensePrograms(),
                    Permission::viewOwnExpensePrograms(),
                    Permission::createShifts(),
                    Permission::deleteShifts(),
                    Permission::importShifts(),
                    Permission::listShifts(),
                    Permission::updateShifts(),
                    Permission::viewShifts(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                    Permission::createUsers(),
                    Permission::deleteUsers(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 9,
                'name' => '事業所管理者',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::office(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createAttendances(),
                    Permission::deleteAttendances(),
                    Permission::listAttendances(),
                    Permission::updateAttendances(),
                    Permission::viewAttendances(),
                    Permission::createBillings(),
                    Permission::deleteBillings(),
                    Permission::downloadBillings(),
                    Permission::listBillings(),
                    Permission::updateBillings(),
                    Permission::viewBillings(),
                    Permission::createDwsCertifications(),
                    Permission::deleteDwsCertifications(),
                    Permission::updateDwsCertifications(),
                    Permission::viewDwsCertifications(),
                    Permission::createDwsContracts(),
                    Permission::updateDwsContracts(),
                    Permission::viewDwsContracts(),
                    Permission::listDwsProvisionReports(),
                    Permission::updateDwsProvisionReports(),
                    Permission::createLtcsContracts(),
                    Permission::updateLtcsContracts(),
                    Permission::viewLtcsContracts(),
                    Permission::createLtcsInsCards(),
                    Permission::deleteLtcsInsCards(),
                    Permission::updateLtcsInsCards(),
                    Permission::viewLtcsInsCards(),
                    Permission::listLtcsProvisionReports(),
                    Permission::updateLtcsProvisionReports(),
                    Permission::listInternalOffices(),
                    Permission::updateInternalOffices(),
                    Permission::viewInternalOffices(),
                    Permission::createOwnExpensePrograms(),
                    Permission::listOwnExpensePrograms(),
                    Permission::updateOwnExpensePrograms(),
                    Permission::viewOwnExpensePrograms(),
                    Permission::createShifts(),
                    Permission::deleteShifts(),
                    Permission::importShifts(),
                    Permission::listShifts(),
                    Permission::updateShifts(),
                    Permission::viewShifts(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                    Permission::createUserBillings(),
                    Permission::listUserBillings(),
                    Permission::updateUserBillings(),
                    Permission::viewUserBillings(),
                    Permission::createUserDwsCalcSpecs(),
                    Permission::listUserDwsCalcSpecs(),
                    Permission::updateUserDwsCalcSpecs(),
                    Permission::createUserDwsSubsidies(),
                    Permission::updateUserDwsSubsidies(),
                    Permission::viewUserDwsSubsidies(),
                    Permission::createUserLtcsCalcSpecs(),
                    Permission::listUserLtcsCalcSpecs(),
                    Permission::updateUserLtcsCalcSpecs(),
                    Permission::createUserLtcsSubsidies(),
                    Permission::deleteUserLtcsSubsidies(),
                    Permission::updateUserLtcsSubsidies(),
                    Permission::viewUserLtcsSubsidies(),
                    Permission::updateUsersBankAccount(),
                    Permission::createUsers(),
                    Permission::deleteUsers(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 10,
                'name' => 'コーディネーター',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::office(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createAttendances(),
                    Permission::deleteAttendances(),
                    Permission::listAttendances(),
                    Permission::updateAttendances(),
                    Permission::viewAttendances(),
                    Permission::createBillings(),
                    Permission::deleteBillings(),
                    Permission::downloadBillings(),
                    Permission::listBillings(),
                    Permission::updateBillings(),
                    Permission::viewBillings(),
                    Permission::listLtcsProvisionReports(),
                    Permission::updateLtcsProvisionReports(),
                    Permission::viewInternalOffices(),
                    Permission::createOwnExpensePrograms(),
                    Permission::listOwnExpensePrograms(),
                    Permission::updateOwnExpensePrograms(),
                    Permission::viewOwnExpensePrograms(),
                    Permission::createShifts(),
                    Permission::deleteShifts(),
                    Permission::importShifts(),
                    Permission::listShifts(),
                    Permission::updateShifts(),
                    Permission::viewShifts(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                    Permission::createUsers(),
                    Permission::deleteUsers(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 11,
                'name' => '事業所事務担当',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::office(),
                'permissions' => [ // GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::createAttendances(),
                    Permission::deleteAttendances(),
                    Permission::listAttendances(),
                    Permission::updateAttendances(),
                    Permission::viewAttendances(),
                    Permission::createBillings(),
                    Permission::deleteBillings(),
                    Permission::downloadBillings(),
                    Permission::listBillings(),
                    Permission::updateBillings(),
                    Permission::viewBillings(),
                    Permission::listLtcsProvisionReports(),
                    Permission::updateLtcsProvisionReports(),
                    Permission::updateInternalOffices(),
                    Permission::viewInternalOffices(),
                    Permission::createOwnExpensePrograms(),
                    Permission::listOwnExpensePrograms(),
                    Permission::updateOwnExpensePrograms(),
                    Permission::viewOwnExpensePrograms(),
                    Permission::createShifts(),
                    Permission::deleteShifts(),
                    Permission::importShifts(),
                    Permission::listShifts(),
                    Permission::updateShifts(),
                    Permission::viewShifts(),
                    Permission::createStaffs(),
                    Permission::deleteStaffs(),
                    Permission::listStaffs(),
                    Permission::updateStaffs(),
                    Permission::viewStaffs(),
                    Permission::createUsers(),
                    Permission::deleteUsers(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 12,
                'name' => 'ヘルパー',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::person(),
                'permissions' => [// GetIndexRoleCestで引っかかるので、ABC順である必要がある
                    Permission::viewStaffs(),
                ],
            ]),
            $this->generateRole([
                'id' => 13,
                'name' => '管理者',
                'isSystemAdmin' => false,
                'organizationId' => $this->organizations[0]->id,
                'permissions' => $allPermissions, // 全体
                'scope' => RoleScope::whole(), // 全体
            ]),
            $this->generateRole([
                'id' => 14,
                'name' => '権限無し',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::person(),
                'permissions' => [
                ],
            ]),
            $this->generateRole([
                'id' => 15,
                'name' => '契約担当者',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::whole(),
                'permissions' => [
                    Permission::createDwsContracts(),
                    Permission::createLtcsContracts(),
                    Permission::listUsers(),
                    Permission::updateUsers(),
                    Permission::viewUsers(),
                ],
            ]),
            $this->generateRole([
                'id' => 16,
                'name' => '事業所グループ一覧権限を持っているが office の権限',
                'organizationId' => $this->organizations[0]->id,
                'isSystemAdmin' => false,
                'scope' => RoleScope::office(),
                'permissions' => [
                    Permission::listOfficeGroups(),
                ],
            ]),
        ];
    }

    /**
     * Generate an example of Role.
     *
     * @param array $overwrites
     * @return \Domain\Role\Role
     */
    private function generateRole(array $overwrites): Role
    {
        $faker = app(Generator::class);
        $values = [
            'permissions' => [Permission::createStaffs(), Permission::listStaffs(), Permission::viewStaffs()],
            'name' => $faker->text(100),
            'isSystemAdmin' => $faker->boolean,
            'scope' => $faker->randomElement(RoleScope::all()),
            'sortOrder' => $faker->unique()->randomNumber(9, true),
            'createdAt' => Carbon::instance($faker->dateTime),
            'updatedAt' => Carbon::instance($faker->dateTime),
        ];
        return Role::create($overwrites + $values);
    }
}
