// THIS FILE IS AUTO GENERATED BY test/setup/global.ts
// DO NOT EDIT DIRECTLY
import Vue from 'vue'
import ZBankAccountCard from '~/components/domain/bank-account/z-bank-account-card.vue'
import ZBankAccountFormDialog from '~/components/domain/bank-account/z-bank-account-form-dialog.vue'
import ZBankAccountForm from '~/components/domain/bank-account/z-bank-account-form.vue'
import ZBillingFileListCard from '~/components/domain/billing/z-billing-file-list-card.vue'
import ZDwsBillingCopayCoordinationFormDialog from '~/components/domain/billing/z-dws-billing-copay-coordination-form-dialog.vue'
import ZDwsBillingCopayCoordinationForm from '~/components/domain/billing/z-dws-billing-copay-coordination-form.vue'
import ZDwsBillingForm from '~/components/domain/billing/z-dws-billing-form.vue'
import ZDwsBillingStatementListCard from '~/components/domain/billing/z-dws-billing-statement-list-card.vue'
import ZDwsBillingsStatementsForm from '~/components/domain/billing/z-dws-billings-statements-form.vue'
import ZLtcsBillingForm from '~/components/domain/billing/z-ltcs-billing-form.vue'
import ZLtcsBillingStatementItemListCard from '~/components/domain/billing/z-ltcs-billing-statement-item-list-card.vue'
import ZLtcsBillingStatementListCard from '~/components/domain/billing/z-ltcs-billing-statement-list-card.vue'
import ZLtcsBillingStatusAggregateCard from '~/components/domain/billing/z-ltcs-billing-status-aggregate-card.vue'
import ZLtcsBillingsStatementsForm from '~/components/domain/billing/z-ltcs-billings-statements-form.vue'
import ZServiceReportFormatOne from '~/components/domain/billing/z-service-report-format-one.vue'
import ZServiceReportFormatThreeOne from '~/components/domain/billing/z-service-report-format-three-one.vue'
import ZSystemMetaCard from '~/components/domain/common/z-system-meta-card.vue'
import ZContractForm from '~/components/domain/contract/z-contract-form.vue'
import ZContractsCard from '~/components/domain/contract/z-contracts-card.vue'
import ZDwsContractsCard from '~/components/domain/contract/z-dws-contracts-card.vue'
import ZLtcsContractsCard from '~/components/domain/contract/z-ltcs-contracts-card.vue'
import ZDwsCertificationForm from '~/components/domain/dws-certification/z-dws-certification-form.vue'
import ZDwsCertificationsCard from '~/components/domain/dws-certification/z-dws-certifications-card.vue'
import ZLtcsInsCardForm from '~/components/domain/ltcs-ins-card/z-ltcs-ins-card-form.vue'
import ZLtcsInsCardsCard from '~/components/domain/ltcs-ins-card/z-ltcs-ins-cards-card.vue'
import ZHomeHelpServiceCalcSpecForm from '~/components/domain/office/z-home-help-service-calc-spec-form.vue'
import ZHomeHelpServiceCalcSpecsCard from '~/components/domain/office/z-home-help-service-calc-specs-card.vue'
import ZHomeVisitLongTermCareCalcSpecForm from '~/components/domain/office/z-home-visit-long-term-care-calc-spec-form.vue'
import ZHomeVisitLongTermCareCalcSpecsCard from '~/components/domain/office/z-home-visit-long-term-care-calc-specs-card.vue'
import ZOfficeForm from '~/components/domain/office/z-office-form.vue'
import ZOfficeGroupForm from '~/components/domain/office/z-office-group-form.vue'
import ZVisitingCareForPwsdCalcSpecForm from '~/components/domain/office/z-visiting-care-for-pwsd-calc-spec-form.vue'
import ZVisitingCareForPwsdCalcSpecsCard from '~/components/domain/office/z-visiting-care-for-pwsd-calc-specs-card.vue'
import ZSettingForm from '~/components/domain/organization/z-setting-form.vue'
import ZOwnExpenseProgramForm from '~/components/domain/own-expense-program/z-own-expense-program-form.vue'
import ZDwsProjectForm from '~/components/domain/project/z-dws-project-form.vue'
import ZDwsProjectWeeklyServicesCard from '~/components/domain/project/z-dws-project-weekly-services-card.vue'
import ZDwsProjectWeeklyServicesEditCard from '~/components/domain/project/z-dws-project-weekly-services-edit-card.vue'
import ZDwsProjectsCard from '~/components/domain/project/z-dws-projects-card.vue'
import ZLtcsProjectForm from '~/components/domain/project/z-ltcs-project-form.vue'
import ZLtcsProjectWeeklyServicesCard from '~/components/domain/project/z-ltcs-project-weekly-services-card.vue'
import ZLtcsProjectWeeklyServicesEditCard from '~/components/domain/project/z-ltcs-project-weekly-services-edit-card.vue'
import ZLtcsProjectsCard from '~/components/domain/project/z-ltcs-projects-card.vue'
import ZProjectsCard from '~/components/domain/project/z-projects-card.vue'
import ZDwsProvisionReportItemBrowsingDialog from '~/components/domain/provision-report/z-dws-provision-report-item-browsing-dialog.vue'
import ZDwsProvisionReportItemCopyDialog from '~/components/domain/provision-report/z-dws-provision-report-item-copy-dialog.vue'
import ZDwsProvisionReportItemFormDialog from '~/components/domain/provision-report/z-dws-provision-report-item-form-dialog.vue'
import ZLtcsProvisionReportEntryBrowsingDialog from '~/components/domain/provision-report/z-ltcs-provision-report-entry-browsing-dialog.vue'
import ZLtcsProvisionReportEntryFormDialog from '~/components/domain/provision-report/z-ltcs-provision-report-entry-form-dialog.vue'
import ZRoleForm from '~/components/domain/role/z-role-form.vue'
import ZAttendanceForm from '~/components/domain/shift/z-attendance-form.vue'
import ZAttendanceView from '~/components/domain/shift/z-attendance-view.vue'
import ZMyShiftsCard from '~/components/domain/shift/z-my-shifts-card.vue'
import ZShiftDownloadForm from '~/components/domain/shift/z-shift-download-form.vue'
import ZShiftForm from '~/components/domain/shift/z-shift-form.vue'
import ZShiftList from '~/components/domain/shift/z-shift-list.vue'
import ZShiftUploadForm from '~/components/domain/shift/z-shift-upload-form.vue'
import ZShiftView from '~/components/domain/shift/z-shift-view.vue'
import ZIndexPageForm from '~/components/domain/staff/z-index-page-form.vue'
import ZInvitationForm from '~/components/domain/staff/z-invitation-form.vue'
import ZStaffCard from '~/components/domain/staff/z-staff-card.vue'
import ZStaffEditForm from '~/components/domain/staff/z-staff-edit-form.vue'
import ZBillingDestinationCard from '~/components/domain/user-billing/z-billing-destination-card.vue'
import ZUserBillingBulkUploadForm from '~/components/domain/user-billing/z-user-billing-bulk-upload-form.vue'
import ZUserBillingInformationCard from '~/components/domain/user-billing/z-user-billing-information-card.vue'
import ZUserBillingItemCard from '~/components/domain/user-billing/z-user-billing-item-card.vue'
import ZUserBillingItemDetailCard from '~/components/domain/user-billing/z-user-billing-item-detail-card.vue'
import ZUserBillingsView from '~/components/domain/user-billing/z-user-billings-view.vue'
import ZDwsSubsidiesCard from '~/components/domain/user/z-dws-subsidies-card.vue'
import ZDwsSubsidyForm from '~/components/domain/user/z-dws-subsidy-form.vue'
import ZLtcsSubsidiesCard from '~/components/domain/user/z-ltcs-subsidies-card.vue'
import ZLtcsSubsidyForm from '~/components/domain/user/z-ltcs-subsidy-form.vue'
import ZUserCard from '~/components/domain/user/z-user-card.vue'
import ZUserDwsCalcSpecForm from '~/components/domain/user/z-user-dws-calc-spec-form.vue'
import ZUserDwsCalcSpecsCard from '~/components/domain/user/z-user-dws-calc-specs-card.vue'
import ZUserForm from '~/components/domain/user/z-user-form.vue'
import ZUserLtcsCalcSpecForm from '~/components/domain/user/z-user-ltcs-calc-spec-form.vue'
import ZUserLtcsCalcSpecsCard from '~/components/domain/user/z-user-ltcs-calc-specs-card.vue'
import ZUserSummary from '~/components/domain/user/z-user-summary.vue'
import ZActionButton from '~/components/ui/z-action-button.vue'
import ZAppBar from '~/components/ui/z-app-bar.vue'
import ZAutocomplete from '~/components/ui/z-autocomplete.vue'
import ZAvatarMenu from '~/components/ui/z-avatar-menu.vue'
import ZBreadcrumbs from '~/components/ui/z-breadcrumbs.vue'
import ZCancelConfirmDialog from '~/components/ui/z-cancel-confirm-dialog.vue'
import ZCardTitlebar from '~/components/ui/z-card-titlebar.vue'
import ZCheckboxContainer from '~/components/ui/z-checkbox-container.vue'
import ZConfirmDialog from '~/components/ui/z-confirm-dialog.vue'
import ZDataAccordion from '~/components/ui/z-data-accordion.vue'
import ZDataCardHeader from '~/components/ui/z-data-card-header.vue'
import ZDataCardItem from '~/components/ui/z-data-card-item.vue'
import ZDataCard from '~/components/ui/z-data-card.vue'
import ZDataTableFooter from '~/components/ui/z-data-table-footer.vue'
import ZDataTable from '~/components/ui/z-data-table.vue'
import ZDateConfirmDialog from '~/components/ui/z-date-confirm-dialog.vue'
import ZDateField from '~/components/ui/z-date-field.vue'
import ZDatePicker from '~/components/ui/z-date-picker.vue'
import ZErrorContainer from '~/components/ui/z-error-container.vue'
import ZFabSpeedDialButton from '~/components/ui/z-fab-speed-dial-button.vue'
import ZFabSpeedDial from '~/components/ui/z-fab-speed-dial.vue'
import ZFab from '~/components/ui/z-fab.vue'
import ZFileInput from '~/components/ui/z-file-input.vue'
import ZFlexGrow from '~/components/ui/z-flex-grow.vue'
import ZFlexShrink from '~/components/ui/z-flex-shrink.vue'
import ZFlex from '~/components/ui/z-flex.vue'
import ZFormActionButton from '~/components/ui/z-form-action-button.vue'
import ZFormCardItemSet from '~/components/ui/z-form-card-item-set.vue'
import ZFormCardItem from '~/components/ui/z-form-card-item.vue'
import ZFormCard from '~/components/ui/z-form-card.vue'
import ZFormDialog from '~/components/ui/z-form-dialog.vue'
import ZHourAndMinuteField from '~/components/ui/z-hour-and-minute-field.vue'
import ZKeywordFilterAutocomplete from '~/components/ui/z-keyword-filter-autocomplete.vue'
import ZMenuButtonItem from '~/components/ui/z-menu-button-item.vue'
import ZMenuButton from '~/components/ui/z-menu-button.vue'
import ZMultipleEntryField from '~/components/ui/z-multiple-entry-field.vue'
import ZNavigationDrawer from '~/components/ui/z-navigation-drawer.vue'
import ZNotificationIcon from '~/components/ui/z-notification-icon.vue'
import ZNotification from '~/components/ui/z-notification.vue'
import ZNotifications from '~/components/ui/z-notifications.vue'
import ZNumberInputField from '~/components/ui/z-number-input-field.vue'
import ZOverflowShadow from '~/components/ui/z-overflow-shadow.vue'
import ZPageDialog from '~/components/ui/z-page-dialog.vue'
import ZPage from '~/components/ui/z-page.vue'
import ZPostcodeResolver from '~/components/ui/z-postcode-resolver.vue'
import ZProgress from '~/components/ui/z-progress.vue'
import ZPromptDialog from '~/components/ui/z-prompt-dialog.vue'
import ZSelectItemsPerPage from '~/components/ui/z-select-items-per-page.vue'
import ZSelectSearchCondition from '~/components/ui/z-select-search-condition.vue'
import ZSelect from '~/components/ui/z-select.vue'
import ZSortableTreeItems from '~/components/ui/z-sortable-tree-items.vue'
import ZSortableTree from '~/components/ui/z-sortable-tree.vue'
import ZSubheader from '~/components/ui/z-subheader.vue'
import ZTabsItems from '~/components/ui/z-tabs-items.vue'
import ZTabs from '~/components/ui/z-tabs.vue'
import ZTaskMarker from '~/components/ui/z-task-marker.vue'
import ZTextField from '~/components/ui/z-text-field.vue'
import ZTextarea from '~/components/ui/z-textarea.vue'
import ZValidateErrorMessages from '~/components/ui/z-validate-error-messages.vue'
import ZDate from '~/components/util/z-date.vue'
import ZDatetime from '~/components/util/z-datetime.vue'
import ZDevModeOnly from '~/components/util/z-dev-mode-only.vue'
import ZEraDate from '~/components/util/z-era-date.vue'
import ZEraMonth from '~/components/util/z-era-month.vue'
import ZNuxtChild from '~/components/util/z-nuxt-child.vue'
import ZPromised from '~/components/util/z-promised.vue'
import ZTime from '~/components/util/z-time.vue'
import ZWith from '~/components/util/z-with.vue'

export function setupComponents (): void {
  Vue.component('ZBankAccountCard', ZBankAccountCard)
  Vue.component('ZBankAccountFormDialog', ZBankAccountFormDialog)
  Vue.component('ZBankAccountForm', ZBankAccountForm)
  Vue.component('ZBillingFileListCard', ZBillingFileListCard)
  Vue.component('ZDwsBillingCopayCoordinationFormDialog', ZDwsBillingCopayCoordinationFormDialog)
  Vue.component('ZDwsBillingCopayCoordinationForm', ZDwsBillingCopayCoordinationForm)
  Vue.component('ZDwsBillingForm', ZDwsBillingForm)
  Vue.component('ZDwsBillingStatementListCard', ZDwsBillingStatementListCard)
  Vue.component('ZDwsBillingsStatementsForm', ZDwsBillingsStatementsForm)
  Vue.component('ZLtcsBillingForm', ZLtcsBillingForm)
  Vue.component('ZLtcsBillingStatementItemListCard', ZLtcsBillingStatementItemListCard)
  Vue.component('ZLtcsBillingStatementListCard', ZLtcsBillingStatementListCard)
  Vue.component('ZLtcsBillingStatusAggregateCard', ZLtcsBillingStatusAggregateCard)
  Vue.component('ZLtcsBillingsStatementsForm', ZLtcsBillingsStatementsForm)
  Vue.component('ZServiceReportFormatOne', ZServiceReportFormatOne)
  Vue.component('ZServiceReportFormatThreeOne', ZServiceReportFormatThreeOne)
  Vue.component('ZSystemMetaCard', ZSystemMetaCard)
  Vue.component('ZContractForm', ZContractForm)
  Vue.component('ZContractsCard', ZContractsCard)
  Vue.component('ZDwsContractsCard', ZDwsContractsCard)
  Vue.component('ZLtcsContractsCard', ZLtcsContractsCard)
  Vue.component('ZDwsCertificationForm', ZDwsCertificationForm)
  Vue.component('ZDwsCertificationsCard', ZDwsCertificationsCard)
  Vue.component('ZLtcsInsCardForm', ZLtcsInsCardForm)
  Vue.component('ZLtcsInsCardsCard', ZLtcsInsCardsCard)
  Vue.component('ZHomeHelpServiceCalcSpecForm', ZHomeHelpServiceCalcSpecForm)
  Vue.component('ZHomeHelpServiceCalcSpecsCard', ZHomeHelpServiceCalcSpecsCard)
  Vue.component('ZHomeVisitLongTermCareCalcSpecForm', ZHomeVisitLongTermCareCalcSpecForm)
  Vue.component('ZHomeVisitLongTermCareCalcSpecsCard', ZHomeVisitLongTermCareCalcSpecsCard)
  Vue.component('ZOfficeForm', ZOfficeForm)
  Vue.component('ZOfficeGroupForm', ZOfficeGroupForm)
  Vue.component('ZVisitingCareForPwsdCalcSpecForm', ZVisitingCareForPwsdCalcSpecForm)
  Vue.component('ZVisitingCareForPwsdCalcSpecsCard', ZVisitingCareForPwsdCalcSpecsCard)
  Vue.component('ZSettingForm', ZSettingForm)
  Vue.component('ZOwnExpenseProgramForm', ZOwnExpenseProgramForm)
  Vue.component('ZDwsProjectForm', ZDwsProjectForm)
  Vue.component('ZDwsProjectWeeklyServicesCard', ZDwsProjectWeeklyServicesCard)
  Vue.component('ZDwsProjectWeeklyServicesEditCard', ZDwsProjectWeeklyServicesEditCard)
  Vue.component('ZDwsProjectsCard', ZDwsProjectsCard)
  Vue.component('ZLtcsProjectForm', ZLtcsProjectForm)
  Vue.component('ZLtcsProjectWeeklyServicesCard', ZLtcsProjectWeeklyServicesCard)
  Vue.component('ZLtcsProjectWeeklyServicesEditCard', ZLtcsProjectWeeklyServicesEditCard)
  Vue.component('ZLtcsProjectsCard', ZLtcsProjectsCard)
  Vue.component('ZProjectsCard', ZProjectsCard)
  Vue.component('ZDwsProvisionReportItemBrowsingDialog', ZDwsProvisionReportItemBrowsingDialog)
  Vue.component('ZDwsProvisionReportItemCopyDialog', ZDwsProvisionReportItemCopyDialog)
  Vue.component('ZDwsProvisionReportItemFormDialog', ZDwsProvisionReportItemFormDialog)
  Vue.component('ZLtcsProvisionReportEntryBrowsingDialog', ZLtcsProvisionReportEntryBrowsingDialog)
  Vue.component('ZLtcsProvisionReportEntryFormDialog', ZLtcsProvisionReportEntryFormDialog)
  Vue.component('ZRoleForm', ZRoleForm)
  Vue.component('ZAttendanceForm', ZAttendanceForm)
  Vue.component('ZAttendanceView', ZAttendanceView)
  Vue.component('ZMyShiftsCard', ZMyShiftsCard)
  Vue.component('ZShiftDownloadForm', ZShiftDownloadForm)
  Vue.component('ZShiftForm', ZShiftForm)
  Vue.component('ZShiftList', ZShiftList)
  Vue.component('ZShiftUploadForm', ZShiftUploadForm)
  Vue.component('ZShiftView', ZShiftView)
  Vue.component('ZIndexPageForm', ZIndexPageForm)
  Vue.component('ZInvitationForm', ZInvitationForm)
  Vue.component('ZStaffCard', ZStaffCard)
  Vue.component('ZStaffEditForm', ZStaffEditForm)
  Vue.component('ZBillingDestinationCard', ZBillingDestinationCard)
  Vue.component('ZUserBillingBulkUploadForm', ZUserBillingBulkUploadForm)
  Vue.component('ZUserBillingInformationCard', ZUserBillingInformationCard)
  Vue.component('ZUserBillingItemCard', ZUserBillingItemCard)
  Vue.component('ZUserBillingItemDetailCard', ZUserBillingItemDetailCard)
  Vue.component('ZUserBillingsView', ZUserBillingsView)
  Vue.component('ZDwsSubsidiesCard', ZDwsSubsidiesCard)
  Vue.component('ZDwsSubsidyForm', ZDwsSubsidyForm)
  Vue.component('ZLtcsSubsidiesCard', ZLtcsSubsidiesCard)
  Vue.component('ZLtcsSubsidyForm', ZLtcsSubsidyForm)
  Vue.component('ZUserCard', ZUserCard)
  Vue.component('ZUserDwsCalcSpecForm', ZUserDwsCalcSpecForm)
  Vue.component('ZUserDwsCalcSpecsCard', ZUserDwsCalcSpecsCard)
  Vue.component('ZUserForm', ZUserForm)
  Vue.component('ZUserLtcsCalcSpecForm', ZUserLtcsCalcSpecForm)
  Vue.component('ZUserLtcsCalcSpecsCard', ZUserLtcsCalcSpecsCard)
  Vue.component('ZUserSummary', ZUserSummary)
  Vue.component('ZActionButton', ZActionButton)
  Vue.component('ZAppBar', ZAppBar)
  Vue.component('ZAutocomplete', ZAutocomplete)
  Vue.component('ZAvatarMenu', ZAvatarMenu)
  Vue.component('ZBreadcrumbs', ZBreadcrumbs)
  Vue.component('ZCancelConfirmDialog', ZCancelConfirmDialog)
  Vue.component('ZCardTitlebar', ZCardTitlebar)
  Vue.component('ZCheckboxContainer', ZCheckboxContainer)
  Vue.component('ZConfirmDialog', ZConfirmDialog)
  Vue.component('ZDataAccordion', ZDataAccordion)
  Vue.component('ZDataCardHeader', ZDataCardHeader)
  Vue.component('ZDataCardItem', ZDataCardItem)
  Vue.component('ZDataCard', ZDataCard)
  Vue.component('ZDataTableFooter', ZDataTableFooter)
  Vue.component('ZDataTable', ZDataTable)
  Vue.component('ZDateConfirmDialog', ZDateConfirmDialog)
  Vue.component('ZDateField', ZDateField)
  Vue.component('ZDatePicker', ZDatePicker)
  Vue.component('ZErrorContainer', ZErrorContainer)
  Vue.component('ZFabSpeedDialButton', ZFabSpeedDialButton)
  Vue.component('ZFabSpeedDial', ZFabSpeedDial)
  Vue.component('ZFab', ZFab)
  Vue.component('ZFileInput', ZFileInput)
  Vue.component('ZFlexGrow', ZFlexGrow)
  Vue.component('ZFlexShrink', ZFlexShrink)
  Vue.component('ZFlex', ZFlex)
  Vue.component('ZFormActionButton', ZFormActionButton)
  Vue.component('ZFormCardItemSet', ZFormCardItemSet)
  Vue.component('ZFormCardItem', ZFormCardItem)
  Vue.component('ZFormCard', ZFormCard)
  Vue.component('ZFormDialog', ZFormDialog)
  Vue.component('ZHourAndMinuteField', ZHourAndMinuteField)
  Vue.component('ZKeywordFilterAutocomplete', ZKeywordFilterAutocomplete)
  Vue.component('ZMenuButtonItem', ZMenuButtonItem)
  Vue.component('ZMenuButton', ZMenuButton)
  Vue.component('ZMultipleEntryField', ZMultipleEntryField)
  Vue.component('ZNavigationDrawer', ZNavigationDrawer)
  Vue.component('ZNotificationIcon', ZNotificationIcon)
  Vue.component('ZNotification', ZNotification)
  Vue.component('ZNotifications', ZNotifications)
  Vue.component('ZNumberInputField', ZNumberInputField)
  Vue.component('ZOverflowShadow', ZOverflowShadow)
  Vue.component('ZPageDialog', ZPageDialog)
  Vue.component('ZPage', ZPage)
  Vue.component('ZPostcodeResolver', ZPostcodeResolver)
  Vue.component('ZProgress', ZProgress)
  Vue.component('ZPromptDialog', ZPromptDialog)
  Vue.component('ZSelectItemsPerPage', ZSelectItemsPerPage)
  Vue.component('ZSelectSearchCondition', ZSelectSearchCondition)
  Vue.component('ZSelect', ZSelect)
  Vue.component('ZSortableTreeItems', ZSortableTreeItems)
  Vue.component('ZSortableTree', ZSortableTree)
  Vue.component('ZSubheader', ZSubheader)
  Vue.component('ZTabsItems', ZTabsItems)
  Vue.component('ZTabs', ZTabs)
  Vue.component('ZTaskMarker', ZTaskMarker)
  Vue.component('ZTextField', ZTextField)
  Vue.component('ZTextarea', ZTextarea)
  Vue.component('ZValidateErrorMessages', ZValidateErrorMessages)
  Vue.component('ZDate', ZDate)
  Vue.component('ZDatetime', ZDatetime)
  Vue.component('ZDevModeOnly', ZDevModeOnly)
  Vue.component('ZEraDate', ZEraDate)
  Vue.component('ZEraMonth', ZEraMonth)
  Vue.component('ZNuxtChild', ZNuxtChild)
  Vue.component('ZPromised', ZPromised)
  Vue.component('ZTime', ZTime)
  Vue.component('ZWith', ZWith)
}
