/*
 * Copyright © 2020 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
export type EnvironmentName =
  'APP_DEBUG' |
  'APP_ENV' |
  'MAIL_DRIVER' |
  'MAIL_FROM_ADDRESS' |
  'MAIL_FROM_NAME' |
  'MACKEREL_CONTAINER_PLATFORM' |
  'MACKEREL_ROLES' |
  'QUEUE_CONNECTION' |
  'REDIS_SCHEME' |
  'SQS_KEY' |
  'SQS_PREFIX' |
  'SQS_QUEUE' |
  'SQS_REGION' |
  'SQS_SECRET' |
  'ZINGER_FILENAME_DWS_COPAY_COORDINATION_CSV' |
  'ZINGER_FILENAME_DWS_COPAY_COORDINATION_PDF' |
  'ZINGER_FILENAME_DWS_INVOICE_CSV' |
  'ZINGER_FILENAME_DWS_INVOICE_PDF' |
  'ZINGER_FILENAME_DWS_PROJECT_PDF' |
  'ZINGER_FILENAME_DWS_SERVICE_REPORT_CSV' |
  'ZINGER_FILENAME_DWS_SERVICE_REPORT_PDF' |
  'ZINGER_FILENAME_LTCS_INVOICE_CSV' |
  'ZINGER_FILENAME_LTCS_INVOICE_PDF' |
  'ZINGER_FILENAME_LTCS_PROJECT_PDF' |
  'ZINGER_FILENAME_PLAN_TEMPLATE' |
  'ZINGER_HOST' |
  'ZINGER_INVITATION_LIFETIME_MINUTES' |
  'ZINGER_SERVICE_CODE_API_DWS_11_URL' |
  'ZINGER_SERVICE_CODE_API_DWS_12_URL' |
  'ZINGER_SERVICE_CODE_API_LTCS_URL' |
  'ZINGER_STAFF_ATTENDANCE_CONFIRMATION_FOURTH_AUDIO_URI' |
  'ZINGER_STAFF_ATTENDANCE_CONFIRMATION_THIRD_AUDIO_URI' |
  'ZINGER_URI_APP_DOMAIN'

export type SecretName =
  'APP_KEY' |
  'AWS_BUCKET' |
  'AWS_READONLY_BUCKET' |
  'DB_HOST' |
  'DB_PASSWORD' |
  'DB_USERNAME' |
  'REDIS_HOST' |
  'REDIS_PASSWORD' |
  'ZINGER_GOOGLE_GEOCODING_API_KEY' |
  'ZINGER_SENDGRID_API_KEY' |
  'ZINGER_TWILIO_ACCOUNT_SID' |
  'ZINGER_TWILIO_API_KEY_SECRET' |
  'ZINGER_TWILIO_API_KEY_SID' |
  'ZINGER_TWILIO_FROM_SMS_NUMBER' |
  'ZINGER_TWILIO_FROM_TEL_NUMBER' |
  'ZINGER_URL_SHORTENER_KEY'
