/*
 * Copyright © 2019 EUSTYLE LABORATORY - ALL RIGHTS RESERVED.
 * UNAUTHORIZED COPYING OF THIS FILE, VIA ANY MEDIUM IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.
 */
import { RouterLinkStub } from '@vue/test-utils'
import { createButtonComponentStub } from '~~/test/helpers/create-button-component-stub'
import { createComponentStub } from '~~/test/helpers/create-component-stub'

export const stubs = {
  draggable: true,
  nuxt: true,
  'nuxt-child': true,
  'nuxt-link': RouterLinkStub,
  'router-link': RouterLinkStub,
  transition: true,
  'transition-group': true,
  'v-app-bar': true,
  'v-btn': createButtonComponentStub('v-btn-stub'),
  'v-card': true,
  'v-card-actions': true,
  'v-card-text': true,
  'v-card-title': true,
  'v-chip': true,
  'v-col': true,
  'v-container': true,
  'v-date-picker': true,
  'v-dialog': true,
  'v-divider': true,
  'v-flex': true,
  'v-icon': true,
  'v-img': true,
  'v-layout': true,
  'v-list': true,
  'v-list-group': createComponentStub('v-list-group', ['activator', 'default']),
  'v-list-item': true,
  'v-list-item-action': true,
  'v-list-item-content': true,
  'v-list-item-icon': true,
  'v-list-item-subtitle': true,
  'v-list-item-title': true,
  'v-menu': createComponentStub('v-menu', ['activator', 'default']),
  'v-messages': true,
  'v-overlay': true,
  'v-row': true,
  'v-spacer': true,
  'v-subheader': true,
  'v-tab': true,
  'v-tab-item': true,
  'v-tabs': true,
  'v-tabs-items': true,
  'v-toolbar': true,
  'v-toolbar-title': true,
  'v-tooltip': createComponentStub('v-tooltip', ['activator', 'default']),
  'z-bank-account-card': true,
  'z-card-titlebar': true,
  'z-data-card': createComponentStub('z-data-card', ['actions', 'default', 'header']),
  'z-data-card-item': true,
  'z-fab': createButtonComponentStub('z-fab-stub'),
  'z-fab-speed-dial': true,
  'z-fab-speed-dial-button': true,
  'z-flex': true,
  'z-flex-grow': true,
  'z-flex-shrink': true,
  'z-form-action-button': true,
  'z-form-card': createComponentStub('z-form-card', ['actions', 'default', 'header']),
  'z-form-card-item-set': true,
  'z-menu-button': true,
  'z-menu-button-item': true,
  'z-overflow-shadow': true,
  'z-page': createComponentStub('z-page', ['tabs', 'title', 'default']),
  'z-page-dialog': true,
  'z-postcode-resolver': true,
  'z-progress': true,
  'z-staff-card': true,
  'z-subheader': true,
  'z-system-meta-card': true,
  'z-user-summary': true
}
