name: "ESLint for @zinger/aws"
on:
  pull_request:
    paths:
      - 'packages/aws/**/*.js'
      - 'packages/aws/**/*.ts'
      - '.eslintignore'
      - '.eslintrc.js'
      - '.github/workflows/eslint-aws.yaml'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-node-js
      - name: Run eslint
        run: yarn lint:ci packages/aws
