name: "ESLint for @zinger/enums"
on:
  pull_request:
    paths:
      - 'packages/enums/**/*.js'
      - 'packages/enums/**/*.ts'
      - '.eslintignore'
      - '.eslintrc.js'
      - '.github/workflows/eslint-enums.yaml'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-node-js
      - name: Run eslint
        run: yarn lint:ci packages/enums
