name: "Jest for @zinger/aws"

on:
  pull_request:
    branches:
      - main
      - staging
      - prod
    paths:
      - '.github/workflows/jest-aws.yaml'
      - 'packages/aws/**/*.js'
      - 'packages/aws/**/*.ts'
      - 'packages/enums/lib/*.ts'
      - 'packages/helpers/lib/*.ts'
      - 'tsconfig.json'
      - 'tsconfig-test.json'
      - 'yarn.lock'
  schedule:
    - cron: '58 0 * * 1-5'
  workflow_dispatch:

concurrency:
  group: jest-for-zinger-aws-${{ github.head_ref || github.run_id }}-${{ github.base_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  jest:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' || github.base_ref != 'main' || startsWith(github.head_ref, 'renovate/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-node-js
      - name: Run jest
        run: yarn test:ci:aws
        env:
          TZ: Asia/Tokyo
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: ./.github/actions/notify-to-slack
        with:
          color: danger
          text: AWS のテストでエラーが検出されました。
          url: ${{ secrets.SLACK_WEBHOOK }}
