name: "PHP-CS-Fixer"
on:
  pull_request:
    paths:
      - '**.php'
      - '.php-cs-fixer.php'
      - '.github/workflows/php-cs-fixer.yaml'
jobs:
  php-cs-fixer:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.26.0
        with:
          entrypoint: /usr/local/bin/php-cs-fixer
          args: fix --diff --dry-run
