name: "Pull Request Labeler"
on:
  - pull_request_target
jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@main
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
