name: "Sync Labels"
on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yaml'
jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync labels
        uses: b4b4r07/github-labeler@master
        with:
          config: '.github/labels.yaml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
