name: "Test Slack Notification"

on:
  workflow_dispatch:
    inputs:
      color:
        description: Color of Slack Notification
        type: choice
        options:
          - good
          - warning
          - danger
        required: true
        default: good
      text:
        description: Text of Slack Notification
        required: true
        default: GitHub Actions からの Slack 通知テストです。

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Slack Notification
        uses: ./.github/actions/notify-to-slack
        with:
          color: ${{ github.event.inputs.color }}
          text: ${{ github.event.inputs.text }}
          url: ${{ secrets.SLACK_WEBHOOK }}
